/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulateCheckoutRouteImport } from './routes/simulate-checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegistrarRouteImport } from './routes/_authenticated/registrar'
import { Route as AuthenticatedPresencaRouteImport } from './routes/_authenticated/presenca'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedIdososIndexRouteImport } from './routes/_authenticated/idosos.index'
import { Route as AuthenticatedIdososElderIdRouteImport } from './routes/_authenticated/idosos.$elderId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateCheckoutRoute = SimulateCheckoutRouteImport.update({
  id: '/simulate-checkout',
  path: '/simulate-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistrarRoute = AuthenticatedRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencaRoute = AuthenticatedPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdososIndexRoute =
  AuthenticatedIdososIndexRouteImport.update({
    id: '/idosos/',
    path: '/idosos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdososElderIdRoute =
  AuthenticatedIdososElderIdRouteImport.update({
    id: '/idosos/$elderId',
    path: '/idosos/$elderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/simulate-checkout': typeof SimulateCheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/idosos/$elderId': typeof AuthenticatedIdososElderIdRoute
  '/idosos/': typeof AuthenticatedIdososIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/simulate-checkout': typeof SimulateCheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/idosos/$elderId': typeof AuthenticatedIdososElderIdRoute
  '/idosos': typeof AuthenticatedIdososIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/simulate-checkout': typeof SimulateCheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/presenca': typeof AuthenticatedPresencaRoute
  '/_authenticated/registrar': typeof AuthenticatedRegistrarRoute
  '/_authenticated/idosos/$elderId': typeof AuthenticatedIdososElderIdRoute
  '/_authenticated/idosos/': typeof AuthenticatedIdososIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/simulate-checkout'
    | '/sitemap.xml'
    | '/billing'
    | '/equipe'
    | '/painel'
    | '/presenca'
    | '/registrar'
    | '/idosos/$elderId'
    | '/idosos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/simulate-checkout'
    | '/sitemap.xml'
    | '/billing'
    | '/equipe'
    | '/painel'
    | '/presenca'
    | '/registrar'
    | '/idosos/$elderId'
    | '/idosos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/simulate-checkout'
    | '/sitemap.xml'
    | '/_authenticated/billing'
    | '/_authenticated/equipe'
    | '/_authenticated/painel'
    | '/_authenticated/presenca'
    | '/_authenticated/registrar'
    | '/_authenticated/idosos/$elderId'
    | '/_authenticated/idosos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  SimulateCheckoutRoute: typeof SimulateCheckoutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate-checkout': {
      id: '/simulate-checkout'
      path: '/simulate-checkout'
      fullPath: '/simulate-checkout'
      preLoaderRoute: typeof SimulateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registrar': {
      id: '/_authenticated/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof AuthenticatedRegistrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presenca': {
      id: '/_authenticated/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof AuthenticatedPresencaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idosos/': {
      id: '/_authenticated/idosos/'
      path: '/idosos'
      fullPath: '/idosos/'
      preLoaderRoute: typeof AuthenticatedIdososIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idosos/$elderId': {
      id: '/_authenticated/idosos/$elderId'
      path: '/idosos/$elderId'
      fullPath: '/idosos/$elderId'
      preLoaderRoute: typeof AuthenticatedIdososElderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPresencaRoute: typeof AuthenticatedPresencaRoute
  AuthenticatedRegistrarRoute: typeof AuthenticatedRegistrarRoute
  AuthenticatedIdososElderIdRoute: typeof AuthenticatedIdososElderIdRoute
  AuthenticatedIdososIndexRoute: typeof AuthenticatedIdososIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPresencaRoute: AuthenticatedPresencaRoute,
  AuthenticatedRegistrarRoute: AuthenticatedRegistrarRoute,
  AuthenticatedIdososElderIdRoute: AuthenticatedIdososElderIdRoute,
  AuthenticatedIdososIndexRoute: AuthenticatedIdososIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  SimulateCheckoutRoute: SimulateCheckoutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
